[build-system] 
requires = ["setuptools >= 77.0.3"] 
build-backend = "setuptools.build_meta" 


[project]
name = "python_labs"
version = "02.12.2025" 

[project.optional-dependencies]
dev = [
  "pytest>=8.0", # test coverage
  "pytest-cov>=5.0", # test coverage
  "black>=24.0", # code format
]